name: Error Handling Sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Error
        # エラーでも処理を継続する
        continue-on-error: true
        # あとで実行結果を参照するため、IDを振っておく
        id: execution
        # ファイルが存在しないので、確実にエラーになる
        run: cat no_file

      - name: Error handling
        run: echo "Error handling"

      - name: Exit as error
        if: ${{ steps.execution.outcome == 'failure' }}
        run: exit 1
